[theme]
base = "dark"
primaryColor = "#129E59"
backgroundColor = "#030611"
secondaryBackgroundColor = "#0a0f2a"
textColor = "#f1f5f9"
font = "sans serif"

[server]
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
